global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Microservices
  - job_name: 'deal-setting'
    static_configs:
      - targets: ['deal-setting:8081']
    metrics_path: '/management/prometheus'
    scrape_interval: 30s

  - job_name: 'deal-security'
    static_configs:
      - targets: ['deal-security:8085']
    metrics_path: '/management/prometheus'
    scrape_interval: 30s

  - job_name: 'deal-generator'
    static_configs:
      - targets: ['deal-generator:8083']
    metrics_path: '/management/prometheus'
    scrape_interval: 30s

  - job_name: 'deal-website'
    static_configs:
      - targets: ['deal-website:8087']
    metrics_path: '/management/prometheus'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-main:5432']
    scrape_interval: 30s

  # Keycloak
  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Docker containers
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Node exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
